sudo: false
dist: trusty
language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"
    - ".cache"
script:
 - chmod +x ./ossutil64
 - ./ossutil64 config -e $OSS_ENDPOINT -i $OSS_ID -k $OSS_KEY
 - if [ $TRAVIS_BRANCH  ] && [ $TRAVIS_BRANCH = "master" ]; then
      yarn clean;
      yarn build;
      ls ./build > ./filelist;
      ./ossutil64 cp ./filelist oss://$OSS_BUCKETNAME --update;
      ./ossutil64 cp -r ./build oss://$OSS_BUCKETNAME --update;
   fi
