version: '2'

services:
  fmt:
     depends_on:
       - redis
     build: .
     ports:
       - 23401:23400
     links:
       - redis
     volumes:
       - /etc/web_config.conf:/app/application/web_config.conf
     healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost"]
        interval: 1m30s
        timeout: 10s
        retries: 3
        start_period: 40s

  redis:
     image: redis:alpine

